### ISSUE TITLE
ERROR: No times found in the VCD file

### ISSUE THREAD

**Issue by gsullivan** [impedimentToProgress/ProcessVCD#1]
I get an error when I run with a small VCD file:

java testVCD one-sig.vcd

Exception in thread "main" java.io.IOException: ERROR: No times found in the VCD file
        at vcd.VCD.getLastTime(VCD.java:259)
        at testVCD.main(testVCD.java:89)

My VCD file does have 8 times in it.  Am I using the tool incorrectly?

**Comment by impedimentToProgress** [comment]
Can you pastebin (http://pastebin.com/) the vcd file that you are using?  What tool are you using to generate the VCD file?

**Comment by gsullivan** [comment]
I used VCS:
http://pastebin.com/7Dsz8xWr

**Comment by gsullivan** [comment]
I saw 1000 in the getLastTime code, which made wonder if there is a problem with small VCD files.  So, I tried a much bigger file, and I don't see the same error, but I do get another error:

java testVCD uart.vcd
########################
1 ns 
########################
########################
Last time: 914051
########################
Exception in thread "main" java.io.IOException: ERROR: Variable declaration not in a useable format: $var wire      1 !    pclk  $end
        at vcd.VCD.createSymbolTable(VCD.java:297)
        at vcd.VCD.readValuesFromVCD(VCD.java:327)
        at testVCD.main(testVCD.java:100)

This error goes away if I change:
                String[] parts = line.split(" ");
to:
                String[] parts = line.split("\s+");
in the VCD.java file.  This uart.vcd file was generated with Incisive, and it sometimes uses multiple single spaces between tokens.

**Comment by impedimentToProgress** [comment]
Fixes pushed, thanks.  I couldn't get the split to compile, but if you submit a pull request, I can accept it.  Also know that testVCD.java is for demo purposes only---all the cool stuff is in vcd/.  But, if you want to make a movie of the activity in your design over time, it is great.
